 #include<conio.h>
 #include<iostream.h>

 main()
 {
 	cout<<"********************PERKENALAN******************** \n";
   cout<<"================================================== \n";


   cout<<" Nama Saya :HAMID \n";

   cout<<" NIM		 :12174410 \n";

   cout<<" Alamat    :Desa Cibadung RT01/02 Kec.Gunung sindur Kab.Bogor \n";

   cout<<"       =====Kampus BINA SARANA INFORMATIKA,BSD=====\n";

   getch();
 }
